# Generated by Django 3.2.9 on 2021-11-27 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('expiry_date', models.DateField()),
                ('score', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('L', 'Litre'), ('G', 'Gramme'), ('U', 'Unitaire')], max_length=10)),
                ('tags', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Flago',
        ),
    ]
